theme: jekyll-theme-minimal
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from

layout: redirected
sitemap: false

---
title: Jekyll Redirect 301
redirect_to:
  - http://cnn.com
permalink: /jekyll-redirect/
---